name: Daily Bible Reading Post

on:
  schedule:
    - cron: "0 3 * * *" # runs every day at 6 AM Addis time (5 AM UTC)
  workflow_dispatch:

jobs:
  send-reading:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List files for debugging
        run: ls -R

      - name: Send Daily Reading
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          READING_FILE: "${{ github.workspace }}/readings/G1_Sequential_Bible_Reading_2025-10-05_to_2026-10-09.json"
          TIMEZONE: "Africa/Addis_Ababa"
        run: python scripts/send_reading.py
